<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Str;

class listing1Controller extends Controller
{
    public function show($title)
    {
        $listings = [
            [
                'id' => 1,
                'img' => 'assets/img/list-1.jpg',
                'img1' => 'assets/img/team-1.jpg',
                'title' => 'The Big Bumbble Gym',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 4758',
                'miles' => '2.4 miles',
                'name' => 'Fitness',
                'icon' => 'fa-solid fa-dumbbell',
                'span' => 'catIcon cats-1',
                'plus' => '+2',
                'rating' => '4.5',
                'avarage' => 'good',
                'reviews' => '46 Reviews',
                'btn' => 'Open',
                'color' => 'listOpen',
                'dollar' => '$$$',
                'btn1' => 'Featured',
                'tag' => 'true',
            ],
            [
                'id' => 2,
                'img' => 'assets/img/list-2.jpg',
                'img1' => 'assets/img/team-2.jpg',
                'title' => 'Greenvally Real Estate',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 6150',
                'miles' => '3.7 miles',
                'name' => 'Real Estate',
                'icon' => 'bi bi-house-check',
                'span' => 'catIcon cats-2',
                'plus' => '+2',
                'rating' => '4.3',
                'avarage' => 'midium',
                'reviews' => '35 Reviews',
                'btn' => 'Open',
                'color' => 'listOpen',
                'dollar' => '$$$$',
                'btn1' => '',
                'tag' => 'false',
            ],
            [
                'id' => 3,
                'img' => 'assets/img/list-3.jpg',
                'img1' => 'assets/img/team-3.jpg',
                'title' => 'Shree Wedding Planner',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 4785',
                'miles' => '2.7 miles',
                'name' => 'Weddings',
                'icon' => 'bi bi-lamp',
                'span' => 'catIcon cats-3',
                'plus' => '+1',
                'rating' => '4.8',
                'avarage' => 'excellent py-1 px-2 fw-semibold',
                'reviews' => '12 Reviews',
                'btn' => 'Closed',
                'color' => 'listClose',
                'dollar' => '$$$',
                'btn1' => 'Featured',
                'tag' => 'true',
            ],
            [
                'id' => 4,
                'img' => 'assets/img/list-4.jpg',
                'img1' => 'assets/img/team-4.jpg',
                'title' => 'The Blue Ley Light',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 6358',
                'miles' => '5.2 miles',
                'name' => 'Restaurant',
                'icon' => 'bi bi-cup-straw',
                'span' => 'catIcon cats-4',
                'plus' => '+1',
                'rating' => '4.6',
                'avarage' => 'good',
                'reviews' => '72 Reviews',
                'btn' => 'Open',
                'color' => 'listOpen',
                'dollar' => '$$$$',
                'btn1' => '',
                'tag' => 'false',
            ],
            [
                'id' => 5,
                'img' => 'assets/img/list-5.jpg',
                'img1' => 'assets/img/team-5.jpg',
                'title' => 'Shreya Study Center',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 0210',
                'miles' => '3.8 miles',
                'name' => 'Education',
                'icon' => 'bi bi-mortarboard',
                'span' => 'catIcon cats-5',
                'plus' => '+1',
                'rating' => '4.2',
                'avarage' => 'midium',
                'reviews' => '112 Reviews',
                'btn' => 'Closed',
                'color' => 'listClose',
                'dollar' => '$$$',
                'btn1' => 'Featured',
                'tag' => 'true',
            ],
            [
                'id' => 6,
                'img' => 'assets/img/list-6.jpg',
                'img1' => 'assets/img/team-6.jpg',
                'title' => 'Mahroom Garage & Workshop',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 3251',
                'miles' => '2.4 miles',
                'name' => 'Showroom',
                'icon' => 'bi bi-backpack',
                'span' => 'catIcon cats-6',
                'plus' => '+1',
                'rating' => '4.9',
                'avarage' => 'excellent',
                'reviews' => '52 Reviews',
                'btn' => 'Open',
                'color' => 'listOpen',
                'dollar' => '$$$$',
                'btn1' => '',
                'tag' => 'false',
            ],
            [
                'id' => 7,
                'img' => 'assets/img/list-9.jpg',
                'img1' => 'assets/img/team-7.jpg',
                'title' => 'The Great Dream Palace',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 5426',
                'miles' => '4.2 miles',
                'name' => 'Eat & Drink',
                'icon' => 'bi bi-cup-hot',
                'span' => 'catIcon cats-7',
                'plus' => '+2',
                'rating' => '4.9',
                'avarage' => 'excellent',
                'reviews' => '42 Reviews',
                'btn' => 'Closed',
                'color' => 'listClose',
                'dollar' => '$$$',
                'btn1' => 'Featured',
                'tag' => 'true',
            ],
            [
                'id' => 8,
                'img' => 'assets/img/list-8.jpg',
                'img1' => 'assets/img/team-8.jpg',
                'title' => 'Agroo Spa & Massage Center',
                'desc' => 'Cicero famously orated against his political.',
                'number' => '+42 515 635 2136',
                'miles' => '1.2 miles',
                'name' => 'Spa & Beauty',
                'icon' => 'bi bi-basket2',
                'span' => 'catIcon cats-8',
                'plus' => '+1',
                'rating' => '4.7',
                'avarage' => 'good',
                'reviews' => '76 Reviews',
                'btn' => 'Open',
                'color' => 'listOpen',
                'dollar' => '$$$',
                'btn1' => 'Featured',
                'tag' => 'true',
            ]
        ];

        // Find the course by ID
        $item = collect($listings)->first(function ($listing) use ($title) {
            return Str::slug($listing['title']) === $title;
        });

        // If course not found, return 404 error
        if (!$item) {
            abort(404);
        }

        // Return the view and pass the course data to the view
        return view('single-listing-01', compact('item'));
    }
}